# The name of your add-on.
name: "Frameo Control Backend"
# The version of your add-on.
version: "0.1.0"
# The slug of your add-on.
slug: "frameo_control_addon"
# A short description of your add-on.
description: "Backend service to control a Frameo device via ADB over USB or Network."
# The architecture of your add-on.
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
# This should be false for long-running services.
init: false
# Grant the add-on access to the host's USB devices.
usb: true
# Expose port 5000 to the Home Assistant host.
ports:
  "5000/tcp": 5000
# User-configurable options.
options:
  connection_type: "USB"
  device_serial: ""
  device_host: "192.168.1.100"
  device_port: 5555
# Schema for the options.
schema:
  connection_type: list(USB|Network)
  device_serial: str?
  device_host: str?
  device_port: int?
