# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Frameo Control Backend"
version: "0.1.0"
slug: "frameo_control_addon"
description: "Backend service to control a Frameo device via ADB over USB or Network."
url: "https://github.com/HunorLaczko/ha-frameo-control-addon/tree/main/frameo_control_addon"
arch:
  - aarch64
  - amd64
  - armv7
init: false
# Grant access to the host's USB devices
usb: true
# Expose the API port to Home Assistant
ports:
  "5000/tcp": 5000
# User-configurable options
options:
  connection_type: "USB"
  device_serial: ""
  device_host: "192.168.1.100"
  device_port: 5555
schema:
  connection_type: list(USB|Network)
  device_serial: str?
  device_host: str
  device_port: port
#image: "ghcr.io/hunorlaczko/{arch}-addon-frameo-control"
